name: bump version
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Bump version and push tag
      id: tag_version
      uses: anothrNick/github-tag-action@1.18.0
      env:
        GITHUB_TOKEN: ${{ secrets.GHA_GITHUB_TOKEN }}
        WITH_V: true
